[tool.poetry]
name = "homework-22"
version = "0.1.0"
description = "Домашняя работа 22"
authors = ["Konstantin Kosarew"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.2.7"
psycopg2-binary = "^2.9.11"
python-dotenv = "^1.2.1"
pillow = "^12.0.0"
ipython = "^9.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
