# Generated by Django 5.2.7 on 2025-12-07 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at', 'title'], 'permissions': [('can_edit_product', 'Can edit product'), ('can_unpublish_product', 'Can unpublish _product'), ('can_description_product', 'Can description product'), ('can_add_product', 'Can add product'), ('can_view_product', 'Can view product'), ('can_delete_product', 'Can delete product')], 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_article', to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
    ]
