# Generated by Django 5.2.7 on 2025-12-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_options_article_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at', 'title'], 'permissions': [('can_edit_article', 'Can edit article'), ('can_unpublish_article', 'Can unpublish_article'), ('can_description_article', 'Can description article'), ('can_add_article', 'Can add article'), ('can_view_article', 'Can view article'), ('can_delete_article', 'Can delete article')], 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
    ]
