# Generated by Django 5.2.7 on 2025-11-19 21:09

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', validators=[catalog.models.validate_image_size, catalog.models.validate_image_extension], verbose_name='Фотография'),
        ),
    ]
