# Generated by Django 5.2.7 on 2025-12-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'permissions': [('can_edit_product', 'Can edit product'), ('can_unpublish_product', 'Can unpublish _product'), ('can_description_product', 'Can description product'), ('can_add_product', 'Can add product'), ('can_view_product', 'Can view product'), ('can_delete_product', 'Can delete product')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
